apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-location.fullname" . }}
  labels:
{{ include "backend-location.labels" . | indent 4 }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "backend-location.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
