apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend-location","namespace":"cje"},"spec":{"replicas":2,"selector":{"matchLabels":{"run":"backend-location"}},"template":{"metadata":{"labels":{"run":"backend-location"}},"spec":{"containers":[{"image":"gcr.io/na-csa-msuarez/backend-location:0.0.1","name":"backend-location","ports":[{"containerPort":8081}],"volumeMounts":[{"mountPath":"/config/application.properties","name":"backend-location-properties-volume","subPath":"application.properties"}]}],"volumes":[{"configMap":{"name":"backend-location-properties"},"name":"backend-location-properties-volume"}]}}}}
  creationTimestamp: null
  generation: 1
  name: backend-location
  selfLink: /apis/extensions/v1beta1/namespaces/cje/deployments/backend-location
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: backend-location
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: backend-location
    spec:
      containers:
      - image: gcr.io/na-csa-msuarez/backend-location:0.0.1
        imagePullPolicy: IfNotPresent
        name: backend-location
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/application.properties
          name: backend-location-properties-volume
          subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: backend-location-properties
        name: backend-location-properties-volume
status: {}
